### ISSUE TITLE
Problems with Techozoic Fluid 2.1

### ISSUE THREAD

**Issue by rickg** [jeremyclark13/Techozoic-Fluid#3]
Hello.  I run the website www.carlsbadcrossfit.com.  I have been using your Techozoic Fluid theme and love it.  I recently ran the current 2.1 update, and next thing I know I couldn't access the website.  I couldn't access any part of it... I had to call our host (Bluehost), and they had to switch themes.  This sucks.

As far as I understand, there is is something wrong with the PHP files that is giving an internal error.  Please advise:
Rick@carlsbadcrossfit.com

**Comment by jeremyclark13** [comment]
I've been made aware of an issue with a misnamed function in one file.  This has been fixed and an update pushed the WordPress theme repo ( awaiting approval ).

**Comment by rickg** [comment]
Awesome! Thank you!

**Comment by jeremyclark13** [comment]
Version 2.1.1 is available on the theme repo now. You should be able to update from the dashboard.
