### ISSUE TITLE
Date box/ comment bubble

### ISSUE THREAD

**Issue by kprovance** [jeremyclark13/Techozoic-Fluid#4]
I upgraded WP and the theme last night.  The datebox next to 'posted' is gone, as is the comment bubble that used to be on the right side of the post.  Were these removed on purpose?  If not, I can't figure out how to get them back.

www.kevinprovance.com for a look, but I kicked it back to dev mode, so there is only one sandbox post until I get get this worked out.

Thanks  :)

**Comment by jeremyclark13** [comment]
Yes when updating the styling of the theme I made the design to remove them in favor of the smaller text underneath the title.  The same with the comment bubble.  I removed these to have a cleaner layout.
